{
    'name': 'Propiedades inmobiliarias ATD',
    'version': '16.0.1.0.3',
    'author': 'EXSIMP S.A.',
    'category': 'Sales',
    'summary': 'Gestionar las propiedades inmobiliarias en el módulo de ventas',
    'description': """
        Getsionar la gestión de propiedades inmobiliarias al módulo de ventas.
        Incluir detalles de las propiedades como metros cuadrados, baños, etc.
    """,
    'depends': [
        'base',
        'sale',
        'sale_management',
        'mail',
        # ... other dependencies ...
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/property_type_data.xml',
        'views/property_views.xml',
        'views/property_type_views.xml',
        'views/property_model_views.xml',
        'views/res_company_views.xml',
        'views/res_config_settings_views.xml',
        'views/pago_enganche_views.xml',
        'data/sequence.xml',
        'views/sale_views.xml',
        'views/acuerdo_compra_venta_views.xml',
        'reports/sale_property_report.xml',
        'reports/sale_property_balance.xml',
        'wizards/pago_enganche_receive_wizard_view.xml',
        'reports/acuerdo_compra_venta_report.xml',
        'views/proyecto_views.xml',
        'reports/common_styles.xml',
        'data/pago_enganche_cron.xml',
        'data/pago_enganche_payment_type_data.xml',
        'views/pago_enganche_payment_type_views.xml',
        'reports/pago_enganche_report.xml',
        'data/mail_templates.xml',
        'wizards/pago_enganche_anular_wizard_views.xml',
        'wizards/pago_enganche_edit_wizard_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
}